Add GitHub Actions workflow to build and push Docker images
nuts-foundation/go-didx509-toolkit pull request #18
Opened 2024-11-19 09:17 UTC by rolandgroen

This workflow triggers on commits to the master branch and tag pushes. It builds and pushes Docker images for both release and development versions, supporting multiple architectures.

2024-11-28 08:15 UTC, gerardsn requested changes

2024-11-28 08:15 UTC, gerardsn commented on .github/workflows/build-images.yaml
> +          tags: nutsfoundation/nuts-node:dev
probably no dev image needed. (also wrong tag)

2024-11-28 08:15 UTC, gerardsn commented on .github/workflows/build-images.yaml
> +          images: nutsfoundation/nuts-node
this should not go under `nutsfoundation/nuts-node`

2024-11-28 08:15 UTC, gerardsn commented on .github/workflows/build-images.yaml
> +          password: ${{ secrets.DOCKERHUB_TOKEN }}
pushing this to docker would require setting up branch protection and mandatory code reviews etc. Maybe better to wait a bit and just build locally when needed

2024-11-28 08:19 UTC, gerardsn submitted a review, later dismissed
several references to `master` branch should be replaced with `main` branch

2024-12-18 13:30 UTC, woutslakhorst commented
this also requires strict branch protection and reviews from code owners.

2025-01-21 10:57 UTC, gerardsn commented on .github/workflows/build-images.yaml
> +      - build-images # remove when merged
todo

2025-01-21 10:57 UTC, gerardsn commented on .github/workflows/build-images.yaml
> +      - 'v*'
releases must follow this schema

2025-01-21 10:59 UTC, gerardsn commented
branch protection still needs to be activated before this can be merged

2025-01-24 07:50 UTC, reinkrul commented on Dockerfile
> +             curl
I don't think we need curl, since it's used for healthchecks? (and we have none in the Docker image)

2025-01-24 08:11 UTC, reinkrul commented on .github/workflows/build-images.yaml
> +      - build-images # remove when merged
```suggestion
```

2025-01-24 08:15 UTC, reinkrul approved these changes

2025-01-24 08:41 UTC, merged